import type { Trip, TripActivity, TripDay } from "@/entities/trip"
import { typeSafeRequest } from "@/shared/lib/http"
import type {
  AddActivityPayload,
  AddTripDayPayload,
  CreateTripPayload,
  UpdateTripPayload,
} from "@/shared/schema/trip"
import type { ApiRequestPayload } from "@/shared/types/http"
import { okAsync } from "neverthrow"

const MOCK_TRIPS: Trip[] = [
  {
    id: 1,
    title: "Summer in Tashkent & Samarkand",
    destination: "Tashkent",
    destination_country: "Uzbekistan",
    destination_country_code: "UZ",
    start_date: "2024-06-15",
    end_date: "2024-06-22",
    status: "active",
    total_cost: 2500,
    currency: "USD",
    pace: "balanced",
    vibe_tags: ["cultural", "foodie", "history", "architecture"],
    cover_image_url:
      "https://images.unsplash.com/photo-1528502917093-664446904e54?q=80&w=2070&auto=format&fit=crop",
    session_id: "mock-session-123",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    days: [
      {
        id: 1,
        day_number: 1,
        date: "2024-06-15",
        title: "Arrival and Old City",
        activities: [
          {
            id: 101,
            time: "10:00 AM",
            name: "Chorsu Bazaar",
            category: "attraction",
            description: "Explore the historic market and try local snacks.",
            duration_minutes: 120,
            location: "Chorsu, Tashkent",
            location_lat: 41.3271,
            location_lng: 69.2435,
            cost: 0,
            currency: "USD",
            place_id: "chorsu_1",
            insider_tip: "Try the fresh hot non (bread) from the ovens.",
            booking_required: false,
            order_index: 0,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 102,
            time: "01:00 PM",
            name: "Plov Center",
            category: "restaurant",
            description: "Famous lunch spot for traditional Uzbek Plov.",
            duration_minutes: 60,
            location: "Tashkent TV Tower area",
            location_lat: 41.3467,
            location_lng: 69.2831,
            cost: 15,
            currency: "USD",
            place_id: "plov_center_1",
            insider_tip: "Go early to see the massive cauldrons.",
            booking_required: false,
            order_index: 1,
            is_booked: true,
            confirmation_code: "PLV-2024",
          },
          {
            id: 103,
            time: "03:00 PM",
            name: "Kukeldash Madrasah",
            category: "attraction",
            description: "Medieval architectural monument built in 1570.",
            duration_minutes: 45,
            location: "Old City, Tashkent",
            location_lat: 41.32,
            location_lng: 69.24,
            cost: 2,
            currency: "USD",
            place_id: "kukeldash",
            insider_tip: "Look for the traditional wood carvers inside.",
            booking_required: false,
            order_index: 2,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 104,
            time: "05:00 PM",
            name: "Hast Imam Complex",
            category: "attraction",
            description:
              "The spiritual heart of Tashkent housing the oldest Quran.",
            duration_minutes: 90,
            location: "Zarkaynar St",
            location_lat: 41.33,
            location_lng: 69.24,
            cost: 5,
            currency: "USD",
            place_id: "hast_imam",
            insider_tip: "Dress modestly as this is a religious site.",
            booking_required: false,
            order_index: 3,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 105,
            time: "08:00 PM",
            name: "Navvat Lounge Bar",
            category: "restaurant",
            description: "Modern twist on traditional Uzbek atmosphere.",
            duration_minutes: 120,
            location: "Shota Rustaveli St",
            location_lat: 41.29,
            location_lng: 69.26,
            cost: 30,
            currency: "USD",
            place_id: "navvat",
            insider_tip: "Try the pumpkin somsa, it's a seasonal delight.",
            booking_required: true,
            order_index: 4,
            is_booked: true,
            confirmation_code: "NAV-991",
          },
        ],
      },
      {
        id: 2,
        day_number: 2,
        date: "2024-06-16",
        title: "Modern Tashkent & Metro Exploration",
        activities: [
          {
            id: 201,
            time: "10:00 AM",
            name: "Amir Temur Square",
            category: "attraction",
            description: "Central square featuring the statue of Amir Temur.",
            duration_minutes: 45,
            location: "Amir Temur Ave",
            location_lat: 41.3113,
            location_lng: 69.2797,
            cost: 0,
            currency: "USD",
            place_id: "temur_sq",
            insider_tip: "Great for photos in the morning light.",
            booking_required: false,
            order_index: 0,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 202,
            time: "11:30 AM",
            name: "Applied Arts Museum",
            category: "museum",
            description:
              "Exquisite collection of embroidery, ceramics and jewelry.",
            duration_minutes: 90,
            location: "Rakatboshi St",
            location_lat: 41.3,
            location_lng: 69.27,
            cost: 5,
            currency: "USD",
            place_id: "applied_arts",
            insider_tip: "The building itself is a masterpiece of decor.",
            booking_required: false,
            order_index: 1,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 203,
            time: "01:30 PM",
            name: "Afsona Restaurant",
            category: "restaurant",
            description: "Contemporary interpretation of Uzbek cuisine.",
            duration_minutes: 75,
            location: "Taras Shevchenko St",
            location_lat: 41.3,
            location_lng: 69.28,
            cost: 25,
            currency: "USD",
            place_id: "afsona",
            insider_tip: "The grilled vegetables here are exceptional.",
            booking_required: true,
            order_index: 2,
            is_booked: true,
            confirmation_code: "AFS-112",
          },
          {
            id: 204,
            time: "03:00 PM",
            name: "Tashkent Metro Tour",
            category: "other",
            description: "Explore the world-famous ornate metro stations.",
            duration_minutes: 90,
            location: "Cosmonauts, Alisher Navoi Stations",
            location_lat: 41.3,
            location_lng: 69.26,
            cost: 1,
            currency: "USD",
            place_id: "metro_tour",
            insider_tip: "Cosmonautlar station is a must-see for sci-fi fans.",
            booking_required: false,
            order_index: 3,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 205,
            time: "07:00 PM",
            name: "Tashkent City Park",
            category: "attraction",
            description: "State-of-the-art park with musical fountains.",
            duration_minutes: 120,
            location: "Furkat St",
            location_lat: 41.31,
            location_lng: 69.25,
            cost: 0,
            currency: "USD",
            place_id: "tash_city_park",
            insider_tip: "Fountain show starts precisely at 8:00 PM.",
            booking_required: false,
            order_index: 4,
            is_booked: false,
            confirmation_code: null,
          },
        ],
      },
      {
        id: 3,
        day_number: 3,
        date: "2024-06-17",
        title: "Journey to Samarkand",
        activities: [
          {
            id: 301,
            time: "08:00 AM",
            name: "Afrosiyob High-Speed Train",
            category: "other",
            description: "Comfortable train ride to the ancient city.",
            duration_minutes: 130,
            location: "Tashkent Railway Station",
            location_lat: 41.2925,
            location_lng: 69.27,
            cost: 45,
            currency: "USD",
            place_id: "train_sam",
            insider_tip: "The train provides complimentary snacks and tea.",
            booking_required: true,
            order_index: 0,
            is_booked: true,
            confirmation_code: "AFRO-998",
          },
          {
            id: 302,
            time: "11:00 AM",
            name: "Hotel Check-in & Refresh",
            category: "hotel",
            description: "Settle into your traditional boutique hotel.",
            duration_minutes: 60,
            location: "Samarkand Center",
            location_lat: 39.65,
            location_lng: 66.97,
            cost: 0,
            currency: "USD",
            place_id: "hotel_check",
            insider_tip: "Most hotels offer green tea upon arrival.",
            booking_required: true,
            order_index: 1,
            is_booked: true,
            confirmation_code: "STAY-SAM",
          },
          {
            id: 303,
            time: "01:00 PM",
            name: "Lunch at Labi G'or",
            category: "restaurant",
            description: "Dine overlooking the bustling street life.",
            duration_minutes: 75,
            location: "Near Registan",
            location_lat: 39.65,
            location_lng: 66.98,
            cost: 20,
            currency: "USD",
            place_id: "labi_gor",
            insider_tip: "Their Manti is considered the best in the city.",
            booking_required: false,
            order_index: 2,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 304,
            time: "03:00 PM",
            name: "Registan Square",
            category: "attraction",
            description: "The heart of Samarkand and a UNESCO site.",
            duration_minutes: 180,
            location: "Registan St",
            location_lat: 39.6548,
            location_lng: 66.9757,
            cost: 12,
            currency: "USD",
            place_id: "registan",
            insider_tip: "Climb the minaret for a fee for a bird's eye view.",
            booking_required: false,
            order_index: 3,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 305,
            time: "07:00 PM",
            name: "Gur-e-Amir Mausoleum",
            category: "attraction",
            description: "The magnificent tomb of Tamerlane.",
            duration_minutes: 60,
            location: "Oksaroy St",
            location_lat: 39.64,
            location_lng: 66.96,
            cost: 8,
            currency: "USD",
            place_id: "gure_amir",
            insider_tip: "Spectacular when illuminated at night.",
            booking_required: false,
            order_index: 4,
            is_booked: false,
            confirmation_code: null,
          },
        ],
      },
      {
        id: 4,
        day_number: 4,
        date: "2024-06-18",
        title: "Ancient Architecture",
        activities: [
          {
            id: 401,
            time: "09:00 AM",
            name: "Shah-i-Zinda",
            category: "attraction",
            description: "Breathtaking avenue of turquoise mausoleums.",
            duration_minutes: 120,
            location: "M74 Highway",
            location_lat: 39.6642,
            location_lng: 66.9881,
            cost: 8,
            currency: "USD",
            place_id: "shahi_zinda",
            insider_tip: "Arrive at opening to beat the tourist crowds.",
            booking_required: false,
            order_index: 0,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 402,
            time: "11:30 AM",
            name: "Bibi-Khanym Mosque",
            category: "attraction",
            description: "Once one of the largest mosques in the world.",
            duration_minutes: 60,
            location: "Islohot St",
            location_lat: 39.6608,
            location_lng: 66.9794,
            cost: 6,
            currency: "USD",
            place_id: "bibi_khanym",
            insider_tip:
              "The massive Quran stone stand grants wishes if you walk around it.",
            booking_required: false,
            order_index: 1,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 403,
            time: "01:00 PM",
            name: "Siyob Bazaar",
            category: "shopping",
            description:
              "Vibrant marketplace full of spices and Samarkand bread.",
            duration_minutes: 90,
            location: "Adjacent to Bibi-Khanym",
            location_lat: 39.66,
            location_lng: 66.98,
            cost: 0,
            currency: "USD",
            place_id: "siyob",
            insider_tip: "Buy the famous Samarkand non (bread) here.",
            booking_required: false,
            order_index: 2,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 404,
            time: "03:30 PM",
            name: "Hazrat Khizr Mosque",
            category: "attraction",
            description: "Historic mosque offering panoramic views.",
            duration_minutes: 45,
            location: "Shah-i-Zinda St",
            location_lat: 39.66,
            location_lng: 66.98,
            cost: 3,
            currency: "USD",
            place_id: "hazrat_khizr",
            insider_tip: "The modern mausoleum of Islam Karimov is also here.",
            booking_required: false,
            order_index: 3,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 405,
            time: "07:30 PM",
            name: "Traditional Music Show",
            category: "attraction",
            description: "Evening of local folk music and dance.",
            duration_minutes: 90,
            location: "El Merosi Theater",
            location_lat: 39.65,
            location_lng: 66.96,
            cost: 25,
            currency: "USD",
            place_id: "folk_show",
            insider_tip: "Book through your hotel for better seating.",
            booking_required: true,
            order_index: 4,
            is_booked: true,
            confirmation_code: "SHOW-121",
          },
        ],
      },
      {
        id: 5,
        day_number: 5,
        date: "2024-06-19",
        title: "Artisans of Samarkand",
        activities: [
          {
            id: 501,
            time: "10:00 AM",
            name: "Konigil Paper Mill",
            category: "other",
            description: "Traditional silk paper making demonstration.",
            duration_minutes: 90,
            location: "Konigil Village",
            location_lat: 39.68,
            location_lng: 67.02,
            cost: 5,
            currency: "USD",
            place_id: "paper_mill",
            insider_tip: "The water wheel is extremely peaceful.",
            booking_required: false,
            order_index: 0,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 502,
            time: "12:00 PM",
            name: "Pottery Workshop",
            category: "other",
            description: "Try your hand at traditional blue ceramics.",
            duration_minutes: 60,
            location: "Konigil Village",
            location_lat: 39.68,
            location_lng: 67.02,
            cost: 15,
            currency: "USD",
            place_id: "pottery_sam",
            insider_tip: "It takes 24 hours for items to dry enough to carry.",
            booking_required: false,
            order_index: 1,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 503,
            time: "01:30 PM",
            name: "Samarkand Restaurant",
            category: "restaurant",
            description: "Grand dining hall with live music.",
            duration_minutes: 90,
            location: "Makhmud Kashgari St",
            location_lat: 39.66,
            location_lng: 66.95,
            cost: 40,
            currency: "USD",
            place_id: "sam_rest",
            insider_tip: "Their Shashlik is highly recommended.",
            booking_required: true,
            order_index: 2,
            is_booked: true,
            confirmation_code: "DIN-321",
          },
          {
            id: 504,
            time: "03:30 PM",
            name: "Local Carpet Workshop",
            category: "shopping",
            description: "See hand-woven silk carpets being crafted.",
            duration_minutes: 60,
            location: "Samarkand Old City",
            location_lat: 39.65,
            location_lng: 66.97,
            cost: 0,
            currency: "USD",
            place_id: "carpet_weavers",
            insider_tip:
              "Ask about the natural dyes used from walnut and indigo.",
            booking_required: false,
            order_index: 3,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 505,
            time: "05:30 PM",
            name: "Wine Tasting at Hovrenko",
            category: "other",
            description: "Taste local Samarkand wines and brandy.",
            duration_minutes: 60,
            location: "Makhmud Kashgari St",
            location_lat: 39.66,
            location_lng: 66.95,
            cost: 20,
            currency: "USD",
            place_id: "wine_hovrenko",
            insider_tip:
              "Established in 1868, it's the oldest winery in the region.",
            booking_required: true,
            order_index: 4,
            is_booked: true,
            confirmation_code: "WINE-88",
          },
        ],
      },
      {
        id: 6,
        day_number: 6,
        date: "2024-06-20",
        title: "Observatories & Science",
        activities: [
          {
            id: 601,
            time: "09:00 AM",
            name: "Ulugh Beg Observatory",
            category: "museum",
            description: "Remnants of the great 15th-century space center.",
            duration_minutes: 60,
            location: "Tashkent Rd",
            location_lat: 39.6747,
            location_lng: 67.0064,
            cost: 5,
            currency: "USD",
            place_id: "obsv_ulugh",
            insider_tip: "The museum has amazing medieval star maps.",
            booking_required: false,
            order_index: 0,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 602,
            time: "11:00 AM",
            name: "Tomb of Daniel",
            category: "attraction",
            description: "A pilgrimage site for three world religions.",
            duration_minutes: 45,
            location: "Siyob River",
            location_lat: 39.67,
            location_lng: 67.01,
            cost: 3,
            currency: "USD",
            place_id: "tomb_daniel",
            insider_tip: "The coffin is unusually long (about 18 meters).",
            booking_required: false,
            order_index: 1,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 603,
            time: "01:00 PM",
            name: "Lunch with Local Family",
            category: "other",
            description: "Authentic home-cooked meal in a Mahalla.",
            duration_minutes: 120,
            location: "Samarkand Mahalla",
            location_lat: 39.65,
            location_lng: 66.97,
            cost: 35,
            currency: "USD",
            place_id: "home_lunch",
            insider_tip: "A great way to learn about local customs.",
            booking_required: true,
            order_index: 2,
            is_booked: true,
            confirmation_code: "HOME-99",
          },
          {
            id: 604,
            time: "04:00 PM",
            name: "Afrosiyob Museum",
            category: "museum",
            description: "History of the ancient settlement and frescoes.",
            duration_minutes: 90,
            location: "Afrosiyob Hill",
            location_lat: 39.67,
            location_lng: 66.99,
            cost: 6,
            currency: "USD",
            place_id: "afro_museum",
            insider_tip: "Don't miss the 7th-century wall paintings.",
            booking_required: false,
            order_index: 3,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 605,
            time: "07:30 PM",
            name: "Farewell Dinner at Sim-Sim",
            category: "restaurant",
            description: "High-end traditional Uzbek cuisine.",
            duration_minutes: 120,
            location: "Tashkent City",
            location_lat: 41.31,
            location_lng: 69.28,
            cost: 60,
            currency: "USD",
            place_id: "simsim_rest",
            insider_tip: "Try the lamb chops with pomegranate.",
            booking_required: true,
            order_index: 4,
            is_booked: true,
            confirmation_code: "DIN-882",
          },
        ],
      },
      {
        id: 7,
        day_number: 7,
        date: "2024-06-21",
        title: "Souvenirs and Departure",
        activities: [
          {
            id: 701,
            time: "09:00 AM",
            name: "Independence Square",
            category: "attraction",
            description: "Grand park and government buildings in Tashkent.",
            duration_minutes: 60,
            location: "Mustaqillik Maydoni",
            location_lat: 41.31,
            location_lng: 69.27,
            cost: 0,
            currency: "USD",
            place_id: "indep_sq",
            insider_tip: "Great for a morning stroll before the heat.",
            booking_required: false,
            order_index: 0,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 702,
            time: "11:00 AM",
            name: "Last Minute Shopping",
            category: "shopping",
            description: "Final stop for ceramics and silk scarves.",
            duration_minutes: 120,
            location: "Broadway, Tashkent",
            location_lat: 41.31,
            location_lng: 69.28,
            cost: 100,
            currency: "USD",
            place_id: "souvenira",
            insider_tip: "Rishtan ceramics are the best quality.",
            booking_required: false,
            order_index: 1,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 703,
            time: "01:30 PM",
            name: "Quick Lunch at Central Cafe",
            category: "restaurant",
            description: "Bustling cafe with international options.",
            duration_minutes: 45,
            location: "Tashkent Center",
            location_lat: 41.31,
            location_lng: 69.27,
            cost: 15,
            currency: "USD",
            place_id: "central_cafe",
            insider_tip: "Efficient service if you're in a hurry.",
            booking_required: false,
            order_index: 2,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 704,
            time: "03:00 PM",
            name: "Navoi Opera House",
            category: "attraction",
            description: "Famous theater designed by Alexey Shchusev.",
            duration_minutes: 30,
            location: "Zarafshon St",
            location_lat: 41.31,
            location_lng: 69.27,
            cost: 0,
            currency: "USD",
            place_id: "opera_house",
            insider_tip: "Beautiful even if you just see the facade.",
            booking_required: false,
            order_index: 3,
            is_booked: false,
            confirmation_code: null,
          },
          {
            id: 705,
            time: "06:00 PM",
            name: "Airport Transfer",
            category: "other",
            description: "Private shuttle to Tashkent International Airport.",
            duration_minutes: 30,
            location: "Tashkent City",
            location_lat: 41.3,
            location_lng: 69.27,
            cost: 10,
            currency: "USD",
            place_id: "airport_drop",
            insider_tip: "Allow extra time for security checks.",
            booking_required: true,
            order_index: 4,
            is_booked: true,
            confirmation_code: "FLY-HOME",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Mountain Escape to Chimgan",
    destination: "Chimgan",
    destination_country: "Uzbekistan",
    destination_country_code: "UZ",
    start_date: "2024-08-10",
    end_date: "2024-08-12",
    status: "planning",
    total_cost: 800,
    currency: "USD",
    pace: "active",
    vibe_tags: ["nature", "hiking"],
    cover_image_url:
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=2070&auto=format&fit=crop",
    session_id: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    days: [],
  },
]

export async function listUserTrips(
  payload: ApiRequestPayload<
    undefined,
    { status?: string; limit?: number; offset?: number }
  >,
) {
  // Simulating API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  let trips = [...MOCK_TRIPS]
  if (payload.params?.status) {
    trips = trips.filter((t) => t.status === payload.params?.status)
  }

  return okAsync({ trips, total: trips.length })
}

export async function getTripById(
  payload: ApiRequestPayload<undefined, { tripId: number }>,
) {
  // Simulating API delay
  await new Promise((resolve) => setTimeout(resolve, 500))

  const trip = MOCK_TRIPS.find((t) => t.id === payload.params?.tripId)
  if (!trip) {
    // In a real app we'd return an errAsync here
    return okAsync(MOCK_TRIPS[0]) // Return first one for demo if ID doesn't match
  }

  return okAsync(trip)
}

export async function createTrip(
  payload: ApiRequestPayload<CreateTripPayload>,
) {
  return await typeSafeRequest<CreateTripPayload, undefined, Trip>({
    url: "api/v1/trips",
    method: "post",
    payload,
  })
}

export async function updateTrip(
  payload: ApiRequestPayload<UpdateTripPayload, { tripId: number }>,
) {
  return await typeSafeRequest<UpdateTripPayload, { tripId: number }, Trip>({
    url: `api/v1/trips/${payload.params?.tripId}`,
    method: "patch",
    payload,
  })
}

export async function deleteTrip(
  payload: ApiRequestPayload<undefined, { tripId: number }>,
) {
  return await typeSafeRequest<
    undefined,
    { tripId: number },
    { success: boolean }
  >({
    url: `api/v1/trips/${payload.params?.tripId}`,
    method: "delete",
    payload,
  })
}

export async function addDayToTrip(
  payload: ApiRequestPayload<AddTripDayPayload, { tripId: number }>,
) {
  return await typeSafeRequest<AddTripDayPayload, { tripId: number }, TripDay>({
    url: `api/v1/trips/${payload.params?.tripId}/days`,
    method: "post",
    payload,
  })
}

export async function addActivityToDay(
  payload: ApiRequestPayload<
    AddActivityPayload,
    { tripId: number; dayId: number }
  >,
) {
  return await typeSafeRequest<
    AddActivityPayload,
    { tripId: number; dayId: number },
    TripActivity
  >({
    url: `api/v1/trips/${payload.params?.tripId}/days/${payload.params?.dayId}/activities`,
    method: "post",
    payload,
  })
}

export async function updateActivity(
  payload: ApiRequestPayload<
    Partial<AddActivityPayload>,
    { tripId: number; activityId: number }
  >,
) {
  return await typeSafeRequest<
    Partial<AddActivityPayload>,
    { tripId: number; activityId: number },
    TripActivity
  >({
    url: `api/v1/trips/${payload.params?.tripId}/activities/${payload.params?.activityId}`,
    method: "patch",
    payload,
  })
}

export async function deleteActivity(
  payload: ApiRequestPayload<undefined, { tripId: number; activityId: number }>,
) {
  return await typeSafeRequest<
    undefined,
    { tripId: number; activityId: number },
    { success: boolean }
  >({
    url: `api/v1/trips/${payload.params?.tripId}/activities/${payload.params?.activityId}`,
    method: "delete",
    payload,
  })
}

export async function reorderActivities(
  payload: ApiRequestPayload<{ activity_ids: number[] }, { tripId: number }>,
) {
  return await typeSafeRequest<
    { activity_ids: number[] },
    { tripId: number },
    { message: string }
  >({
    url: `api/v1/trips/${payload.params?.tripId}/activities/reorder`,
    method: "post",
    payload,
  })
}
